flask/__init__.py
from flask import Flask


def create_app(config=None):
    """
    create_app 은 애플리케이션 팩토리 패턴에 따른 함수입니다.

    config 파라미터는 테스트에 필요하니 변경하지는 말아주세요!
    """
    app = Flask(__name__)
    
    # 여기에서 주어진 config 에 따라 추가 설정을 합니다.
    if config is not None:
        app.config.update(config)

    from views.error import error_bp 
    from views.home import home_bp
    from views.predict import predict_bp
    from views.recommand import recommand_bp

    app.register_blueprint(error_bp)
    app.register_blueprint(home_bp)
    app.register_blueprint(predict_bp)
    app.register_blueprint(recommand_bp)

    return app

if __name__ == "__main__":
  app = create_app()
  app.run()

flask/views/error.py
from flask import Blueprint, render_template

error_bp = Blueprint('error', __name__)

@error_bp.errorhandler(404)
def page_not_found(error):
    return render_template('404.html'), 404

flask/views/home.py
from flask import Blueprint, render_template, request
import requests
import json
from dotenv import load_dotenv
import os

load_dotenv()

home_bp = Blueprint('home', __name__)
@home_bp.route('/', methods=['GET', 'POST'])
def home():
    if request.method == 'GET' :
        return render_template('home.html')
    
    if request.method == 'POST' :
        try : 
            date = request.form['날짜']
            weather_date = int(date.replace('-','').strip())

            key = os.environ.get('key')
            
            startDate = weather_date - 10000
            endDate =  startDate
            location = 108

            url = f'http://apis.data.go.kr/1360000/AsosDalyInfoService/getWthrDataList?serviceKey={key}&pageNo=1&numOfRows=999&dataType=JSON&dataCd=ASOS&dateCd=DAY&startDt={startDate}&endDt={endDate}&stnIds={location}'

            raw_data = requests.get(url)
            parsed_data = json.loads(raw_data.text)
            weather_data = parsed_data['response']['body']['items']['item']
        
            return render_template('home_api.html', weather_data=weather_data, date=date), 200
        
        except :
            return render_template("404.html")

flask/views/predict.py
from flask import Blueprint, render_template, request
import numpy as np
import pickle


model = pickle.load(open('model.pkl', 'rb'))

predict_bp = Blueprint('predict', __name__)
@predict_bp.route('/predict', methods=['GET', 'POST'])
def predict():
    if request.method == 'GET' :
        return render_template('predict.html')

    if request.method == 'POST' :
        try : 
            data1 = float(request.form['평균기온'])
            data2 = float(request.form['최저기온'])
            data3 = float(request.form['최고기온'])
            data4 = float(request.form['합계일조시간'])
            data5 = float(request.form['평균풍속'])
            data6 = float(request.form['평균상대습도'])

            arr = np.array([[data1, data2, data3, data4, data5, data6]])
            pred = model.predict(arr)
            pred = round(pred[0])

            return render_template('predict_result.html', pred=pred)
            
        except :
            return render_template("404.html")

flask/views/recommand.py
from flask import Blueprint, render_template, request
import requests
from dotenv import load_dotenv
import os

load_dotenv()

recommand_bp = Blueprint('recommand', __name__)

@recommand_bp.route('/recommand', methods=['GET', 'POST'])
def recommand():
    if request.method == 'GET' :
        return render_template('recommand_home.html')

    if request.method == 'POST' :
        try :
            ncreds = {

                    "client_id": os.environ.get('client_id'),
                    "client_secret" : os.environ.get('client_secret')

                 }
            nheaders = {
                            "X-Naver-Client-Id" : ncreds.get('client_id'),
                            "X-Naver-Client-Secret" : ncreds.get('client_secret')
                        }

            naver_local_url = "https://openapi.naver.com/v1/search/local.json?"

            location = request.form['지역']

            recommands = []
            query = location + " " + " 맛집"
            params = "sort=comment" + "&query=" + query + "&display=" + '20'
                
            res = requests.get(naver_local_url + params, headers=nheaders)
            result_list = res.json().get('items')

            for i in range(0,5):
                recommands.append(result_list[i])

            return render_template('recommand.html', recommand=recommands, location=location)

        except :
            return render_template("404.html")

flask/templates/after.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% if pred %}
    <h1>이러한 날씨변수를 가지는 날의 지하철 예상 승객수는<br>{{ pred }}명 입니다.</h1>
    {% endif %}
    <a href='/'>go back to home page</a>
</body>
</html>

flask/templates/home.html
<!DOCTYPE HTML>
<html>
    <head>
        <title>당신의 나들이</title>
        <meta charset="utf-8"/>
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1, user-scalable=no"/>
        <link rel="stylesheet" href="../static/css/main.css"/>
        <noscript><link rel="stylesheet" href="../static/css/noscript.css"/></noscript>
    </head>

    <body class="landing is-preload">

        <!-- Page Wrapper -->
        <div id="page-wrapper">

            <!-- Header -->
            <header id="header" class="alt">
                <h1>
                    <a href="/">당신의 나들이</a>
                </h1>
                <nav id="nav">
                    <ul>
                        <li class="special">
                            <a href="#menu" class="menuToggle">
                                <span>Menu</span></a>
                            <div id="menu">
                                <ul>
                                    <li>
                                        <a href="/">Home</a>
                                    </li>
                                    <li>
                                        <a href="/predict">Prediction</a>
                                    </li>
                                    <li>
                                        <a href="/recommand">Recommend</a>
                                    </li>
                                    <li>
                                        <a href="https://velog.io/@bgly">Contact Us</a>
                                    </li>
                                </ul>
                            </div>
                        </li>
                    </ul>
                </nav>
            </header>

            <!-- Banner -->
            <section id="banner">
                <div class="inner">
                    <h2>당신의 나들이</h2>
                    <p>오늘의 날씨와 지하철 예상승객수,<br/>
                        그리고 주변 맛집까지<br/>
                        모두 알려드릴게요</p><br/>
                    <h6>날짜를 입력해주세요</h6>

                    <ul class="actions special">
                        <form method="POST" ,="," action="{{url_for('home.home')}}">
                            <li><input type="date" name='날짜' placeholder="날짜 입력"></li><br/>
                            <li>
                                <button type="submit" class="button primary">Search</button>
                            </li>
                        </form>
                    </ul>
                </div>
                <a href="#one" class="more scrolly">CREATED BY</a>
            </section>

            <!-- CTA -->
            <section id="cta" class="wrapper style4">
                <div class="inner">
                    <header>
                        <h2>현 채 원</h2>
                        <br>세상의 많은 데이터가 더 많이 활용될 수 있도록</p>
                </header>
                <ul class="actions stacked">
                    <li>
                        <a href="https://github.com/chaiwon1" class="button fit primary">GITHUB</a>
                    </li>
                    <li>
                        <a href="https://velog.io/@bgly" class="button fit">BLOG</a>
                    </li>
                </ul>
            </div>
        </section>

        <!-- Footer -->
        <footer id="footer">
            <ul class="copyright">
                <p>해당 페이지는 코드스테이츠 AI 부트캠프 프로젝트를 위해 제작되었습니다.<br/>
                    기상청, 서울 공공데이터, 네이버 검색 OPEN API를 사용하였습니다.<br/>
                    머신러닝 모델은 Randomforest 모델을 사용하였습니다.</p>
                <li>기획 :
                    <a href="https://github.com/chaiwon1/AI_13_section3_project">현 채 원</a>
                </li>
                <li>Design:
                    <a href="http://html5up.net">HTML5 UP</a>
                </li>
            </ul>
        </footer>

    </div>

    <!-- Scripts -->
    <script src="../static/js/jquery.min.js"></script>
    <script src="../static/js/jquery.scrollex.min.js"></script>
    <script src="../static/js/jquery.scrolly.min.js"></script>
    <script src="../static/js/browser.min.js"></script>
    <script src="../static/js/breakpoints.min.js"></script>
    <script src="../static/js/util.js"></script>
    <script src="../static/js/main.js"></script>

</body>

</html>

flask/templates/home_api.html
<!DOCTYPE HTML>
<html>
    <head>
        <title>당신의 나들이</title>
        <meta charset="utf-8"/>
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1, user-scalable=no"/>
        <link rel="stylesheet" href="../static/css/main.css"/>
        <noscript><link rel="stylesheet" href="../static/css/noscript.css"/></noscript>
    </head>

    <body class="landing is-preload">

        <!-- Page Wrapper -->
        <div id="page-wrapper">

            <!-- Header -->
            <header id="header" class="alt">
                <h1>
                    <a href="/">당신의 나들이</a>
                </h1>
                <nav id="nav">
                    <ul>
                        <li class="special">
                            <a href="#menu" class="menuToggle">
                                <span>Menu</span></a>
                            <div id="menu">
                                <ul>
                                    <li>
                                        <a href="/">Home</a>
                                    </li>
                                    <li>
                                        <a href="/predict">Prediction</a>
                                    </li>
                                    <li>
                                        <a href="/recommand">Recommend</a>
                                    </li>
                                    <li>
                                        <a href="https://velog.io/@bgly">Contact Us</a>
                                    </li>
                                </ul>
                            </div>
                        </li>
                    </ul>
                </nav>
            </header>

            <!-- Banner -->
            <section id="banner">
                <div class="inner">
                    <h2>
                        당신의 나들이 날<br>
                        {{ date }}의</h2>
                    <div class="row">
                        <ul class="alt">
                            {% for item in weather_data %}
                                <li>예상평균기온은<br>{{ item['avgTa'] }}도입니다.</li>
                                <li>예상최저기온은<br>{{ item['minTa'] }}도입니다.</li>
                                <li>예상최고기온은<br>{{ item['maxTa'] }}도입니다.</li>
                                <li>예상합계일조시간은<br>{{ item['sumSsHr'] }}시간입니다.</li>
                                <li>예상평균풍속은<br>{{ item['avgWs'] }}m/h입니다.</li>
                                <li>예상평균상대습도는<br>{{ item['avgRhm'] }}%입니다.</li>
                            {% endfor %}
                        </ul>
                        <ul class="actions special">
                            <li>
                                <a href="/predict" class="button primary small">지하철 탑승객 예측</a>
                            </li>
                            <li>
                                <a href="/recommand" class="button small">맛집 추천</a>
                            </li>
                            <li>
                                <a href="/" class="button small">처음으로</a>
                            </li>
                        </ul>

                    </div>
                </div>

            </section>

            <!-- Footer -->
            <footer id="footer">
                <ul class="copyright">
                    <p>해당 페이지는 코드스테이츠 AI 부트캠프 프로젝트를 위해 제작되었습니다.<br/>
                        기상청, 서울 공공데이터, 네이버 검색 OPEN API를 사용하였습니다.<br/>
                        머신러닝 모델은 Randomforest 모델을 사용하였습니다.</p>
                    <li>기획 :
                        <a href="https://github.com/chaiwon1/AI_13_section3_project">현 채 원</a>
                    </li>
                    <li>Design:
                        <a href="http://html5up.net">HTML5 UP</a>
                    </li>
                </ul>
            </footer>

        </div>

        <!-- Scripts -->
        <script src="../static/js/jquery.min.js"></script>
        <script src="../static/js/jquery.scrollex.min.js"></script>
        <script src="../static/js/jquery.scrolly.min.js"></script>
        <script src="../static/js/browser.min.js"></script>
        <script src="../static/js/breakpoints.min.js"></script>
        <script src="../static/js/util.js"></script>
        <script src="../static/js/main.js"></script>

    </body>

</html>

flask/templates/predict.html
<!DOCTYPE HTML>
<html>
    <head>
        <title>당신의 나들이</title>
        <meta charset="utf-8"/>
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1, user-scalable=no"/>
        <link rel="stylesheet" href="../static/css/main.css"/>
        <noscript><link rel="stylesheet" href="../static/css/noscript.css"/></noscript>
    </head>

    <body class="is-preload">
        <!-- Page Wrapper -->
        <div id="page-wrapper">

            <!-- Header -->
            <header id="header">
                <h1>
                    <a href="/">당신의 나들이</a>
                </h1>
                <nav id="nav">
                    <ul>
                        <li class="special">
                            <a href="#menu" class="menuToggle">
                                <span>Menu</span></a>
                            <div id="menu">
                                <ul>
                                    <li>
                                        <a href="/">Home</a>
                                    </li>
                                    <li>
                                        <a href="/predict">Prediction</a>
                                    </li>
                                    <li>
                                        <a href="/recommand">Recommend</a>
                                    </li>
                                    <li>
                                        <a href="https://velog.io/@bgly">Contact Us</a>
                                    </li>
                                </ul>
                            </div>
                        </li>
                    </ul>
                </nav>
            </header>

            <!-- Main -->
            <article id="main">
                <header>
                    <h2>예상 지하철 탑승객 수</h2>
                    <p>기상정보를 기반으로 서울 지하철 예상 탑승객 수를 알려드릴게요</p>
                </header>
                <section class="wrapper style5">
                    <div class="inner">

                        <section>
                            <h4>기상정보를 입력해주세요</h4>
                            <form method="POST" ,="," action="{{url_for('predict.predict')}}">
                                <div class="row gtr-uniform">
                                    <form method="POST" ,="," action="{{url_for('predict.predict')}}">
                                    <div class="col-6 col-12-xsmall">
                                        <input type="text" name="평균기온" id="demo-name" value="" placeholder="평균기온"/>
                                    </div>
                                    <div class="col-6 col-12-xsmall">
                                        <input type="text" name="최저기온" id="demo-name" value="" placeholder="최저기온"/>
                                    </div>
                                    <div class="col-6 col-12-xsmall">
                                        <input type="text" name="최고기온" id="demo-name" value="" placeholder="최고기온"/>
                                    </div>
                                    <div class="col-6 col-12-xsmall">
                                        <input type="text" name="합계일조시간" id="demo-name" value="" placeholder="합계일조시간"/>
                                    </div>
                                    <div class="col-6 col-12-xsmall">
                                        <input type="text" name="평균풍속" id="demo-name" value="" placeholder="평균풍속"/>
                                    </div>
                                    <div class="col-6 col-12-xsmall">
                                        <input type="text" name="평균상대습도" id="demo-name" value="" placeholder="평균상대습도"/>
                                    </div>
                                    <ul class="actions special">
                                        <li><input type="submit" value="Predict" class="primary"/></li>
                                        <li><input type="reset" value="Reset"/></li>
                                    </ul>
                                </div>
                            </form>
                        </section>
                    </div>
                </article>

                <!-- Footer -->
                <footer id="footer">
                    <ul class="copyright">
                        <p>해당 페이지는 코드스테이츠 AI 부트캠프 프로젝트를 위해 제작되었습니다.<br/>
                            기상청, 서울 공공데이터, 네이버 검색 OPEN API를 사용하였습니다.<br/>
                            머신러닝 모델은 Randomforest 모델을 사용하였습니다.</p>
                        <li>기획 :
                            <a href="https://github.com/chaiwon1/AI_13_section3_project">현 채 원</a>
                        </li>
                        <li>Design:
                            <a href="http://html5up.net">HTML5 UP</a>
                        </li>
                    </ul>
                </footer>

            </div>

            <!-- Scripts -->
            <script src="../static/js/jquery.min.js"></script>
            <script src="../static/js/jquery.scrollex.min.js"></script>
            <script src="../static/js/jquery.scrolly.min.js"></script>
            <script src="../static/js/browser.min.js"></script>
            <script src="../static/js/breakpoints.min.js"></script>
            <script src="../static/js/util.js"></script>
            <script src="../static/js/main.js"></script>

        </body>

    </html>

flask/templates/predict_result.html
<!DOCTYPE HTML>
<html>
    <head>
        <title>당신의 나들이</title>
        <meta charset="utf-8"/>
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1, user-scalable=no"/>
        <link rel="stylesheet" href="../static/css/main.css"/>
        <noscript><link rel="stylesheet" href="../static/css/noscript.css"/></noscript>
    </head>

    <body class="landing is-preload">

        <!-- Page Wrapper -->
        <div id="page-wrapper">

            <!-- Header -->
            <header id="header" class="alt">
                <h1>
                    <a href="/">당신의 나들이</a>
                </h1>
                <nav id="nav">
                    <ul>
                        <li class="special">
                            <a href="#menu" class="menuToggle">
                                <span>Menu</span></a>
                            <div id="menu">
                                <ul>
                                    <li>
                                        <a href="/">Home</a>
                                    </li>
                                    <li>
                                        <a href="/predict">Prediction</a>
                                    </li>
                                    <li>
                                        <a href="/recommand">Recommend</a>
                                    </li>
                                    <li>
                                        <a href="https://velog.io/@bgly">Contact Us</a>
                                    </li>
                                </ul>
                            </div>
                        </li>
                    </ul>
                </nav>
            </header>

            <!-- Banner -->
            <section id="banner">
                <div class="inner">
                    <h2>당신의 나들이 날{{ date }}의</h2>
                    {% if pred %}
                        <h3>지하철 예상 이용객수는<br>{{ pred }}명 입니다.</h3><br/>
                    {% endif %}
                    {% if pred > 3538305.15 %}
                        <h4>평소보다 지하철 이용객수가 많습니다.<br/>다른 교통수단을 이용해보시는 것은 어떨까요?</h4>
                    {% else %}
                        <h4>평소보다 지하철 이용객수가 적습니다.<br/>쾌적한 지하철을 이용하실 수 있습니다</h4>
                    {% endif %}

                    <ul class="actions special">
                        <li>
                            <a href="/recommand" class="button primary small">맛집 추천</a>
                        </li>
                        <li>
                            <a href="/" class="button small">처음으로</a>
                    </ul>
                </div>
            </section>

            <!-- Footer -->
            <footer id="footer">
                <ul class="copyright">
                    <p>해당 페이지는 코드스테이츠 AI 부트캠프 프로젝트를 위해 제작되었습니다.<br/>
                        기상청, 서울 공공데이터, 네이버 검색 OPEN API를 사용하였습니다.<br/>
                        머신러닝 모델은 Randomforest 모델을 사용하였습니다.</p>
                    <li>&기획 :
                        <a href="https://github.com/chaiwon1/AI_13_section3_project">현 채 원</a>
                    </li>
                    <li>Design:
                        <a href="http://html5up.net">HTML5 UP</a>
                    </li>
                </ul>
            </footer>

        </div>

        <!-- Scripts -->
        <script src="../static/js/jquery.min.js"></script>
        <script src="../static/js/jquery.scrollex.min.js"></script>
        <script src="../static/js/jquery.scrolly.min.js"></script>
        <script src="../static/js/browser.min.js"></script>
        <script src="../static/js/breakpoints.min.js"></script>
        <script src="../static/js/util.js"></script>
        <script src="../static/js/main.js"></script>

    </body>

</html>

flask/templates/recommand_home.html
<!DOCTYPE HTML>
<html>
    <head>
        <title>당신의 나들이</title>
        <meta charset="utf-8"/>
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1, user-scalable=no"/>
        <link rel="stylesheet" href="../static/css/main.css"/>
        <noscript><link rel="stylesheet" href="../static/css/noscript.css"/></noscript>
    </head>

    <body class="is-preload">
        <!-- Page Wrapper -->
        <div id="page-wrapper">

            <!-- Header -->
            <header id="header">
                <h1>
                    <a href="/">당신의 나들이</a>
                </h1>
                <nav id="nav">
                    <ul>
                        <li class="special">
                            <a href="#menu" class="menuToggle">
                                <span>Menu</span></a>
                            <div id="menu">
                                <ul>
                                    <li>
                                        <a href="/">Home</a>
                                    </li>
                                    <li>
                                        <a href="/predict">Prediction</a>
                                    </li>
                                    <li>
                                        <a href="/recommand">Recommend</a>
                                    </li>
                                    <li>
                                        <a href="https://velog.io/@bgly">Contact Us</a>
                                    </li>
                                </ul>
                            </div>
                        </li>
                    </ul>
                </nav>
            </header>

            <!-- Main -->
            <article id="main">
                <header>
                    <h2>주변 맛집 추천</h2>
                    <p>나들이 갈 서울 지역의 주변 맛집을 알려드릴게요</p>
                </header>
                <section class="wrapper style5">
                    <div class="inner">

                        <section>
                            <h4 style="text-align:center">나들이 갈 서울 지역</h4>
                            <div class="row gtr-uniform" style="display:inherit">
                                <form method="POST" ,="," action="{{url_for('recommand.recommand')}}">
                                    <div class="col-6 col-12-xsmall">
                                        <input type="text" name="지역" id="demo-name" value="" placeholder="지역을 입력해주세요"/>
                                    </div>
                                    <ul class="actions special">
                                        <li><input type="submit" value="Recommend" class="primary"/></li>
                                        <li><input type="reset" value="Reset"/></li>
                                    </ul>
                                </form>
                            </div>

                        </section>
                    </article>
                    <!-- Footer -->
                    <footer id="footer">
                        <ul class="copyright">
                            <p>해당 페이지는 코드스테이츠 AI 부트캠프 프로젝트를 위해 제작되었습니다.<br/>
                                기상청, 서울 공공데이터, 네이버 검색 OPEN API를 사용하였습니다.<br/>
                                머신러닝 모델은 Randomforest 모델을 사용하였습니다.</p>
                            <li>기획 :
                                <a href="https://github.com/chaiwon1/AI_13_section3_project">현 채 원</a>
                            </li>
                            <li>Design:
                                <a href="http://html5up.net">HTML5 UP</a>
                            </li>
                        </ul>
                    </footer>

                </div>

                <!-- Scripts -->
                <script src="../static/js/jquery.min.js"></script>
                <script src="../static/js/jquery.scrollex.min.js"></script>
                <script src="../static/js/jquery.scrolly.min.js"></script>
                <script src="../static/js/browser.min.js"></script>
                <script src="../static/js/breakpoints.min.js"></script>
                <script src="../static/js/util.js"></script>
                <script src="../static/js/main.js"></script>

            </body>

        </html>